replicaCount: 1

image:
  repository: myapp
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  port: 8080

environment: dev

resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi